[build]
  command = "CI='' npm run build"
  publish = "build"
  base = ""

[build.environment]
  REACT_APP_FIREBASE_API_KEY = "AIzaSyCQQ_d8utjf2vj2MqNhrhlosBrnZQ9o8cs"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "madaperfect-11420.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "madaperfect-11420"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "madaperfect-11420.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "812266852874"
  REACT_APP_FIREBASE_APP_ID = "1:812266852874:web:38622eedeafe51faaf45f3"
  REACT_APP_FIREBASE_MEASUREMENT_ID = "G-V7TSVHRVD1"
